FROM tomcat:8.0.53-jre8
RUN cd /tmp && \
   curl -LO "http://download.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip" -H 'Cookie: oraclelicense=accept-securebackup-cookie' && \
   unzip jce_policy-8.zip && \
   cp -v UnlimitedJCEPolicyJDK8/*.jar $JAVA_HOME/lib/security && \
   rm -rf UnlimitedJCEPolicy* jce_policy-8.zip
