FROM ubuntu:trusty

RUN apt-get update && apt-get install zip -y && apt-get install wget -y && apt-get install curl -y && apt-get install ant -y && apt-get install openjdk-7-jdk -y
RUN apt-get update && cd /tmp && \
   curl -LO "http://download.oracle.com/otn-pub/java/jce/7/UnlimitedJCEPolicyJDK7.zip" -H 'Cookie: oraclelicense=accept-securebackup-cookie' && \
   unzip UnlimitedJCEPolicyJDK7.zip && \
   cp -v UnlimitedJCEPolicy/*.jar /usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/lib/security && \
   rm -rf UnlimitedJCEPolicyJDK7.zip